# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["posts", "oldposts"]
# robots = ""

[header]
  layout = "basic" # valid options: basic, hamburger, custom

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true 
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = false

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/major/major.io/blob/main/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = false
  sharingLinks = ["mastodon", "email", "reddit", "facebook", "twitter", "pinterest", "linkedin"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  groupByYear = true

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
