image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo
  - cp -av public/feed/index.xml public/feed/index.html
  artifacts:
    paths:
    - public
  only:
  - master


