variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_VERSION: "0.54.0"

stages:
  - build
  - deploy

pages:
  image: monachus/hugo
  stage: build
  script:
    - ./build-site.sh
  artifacts:
    paths:
      - public
  only:
    - master

build:blog:
  image: monachus/hugo
  stage: build
  script:
    - ./build-site.sh
  artifacts:
    paths:
      - public

deploy:firebase:
  image: node:latest
  stage: deploy
  dependencies:
    - build:blog
  script:
    - npm install -g firebase-tools
    - firebase use major-io-1f024 --token ${FIREBASE_TOKEN}
    - firebase deploy -m "GitLab Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token ${FIREBASE_TOKEN}
  cache:
    paths:
      - node_modules/
  only:
    - master
