variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_VERSION: "0.54.0"

pages:
  image: monachus/hugo
  script:
    - ./build-site.sh
  artifacts:
    paths:
      - public
  only:
    - master

firebase_deploy:
  image: node:latest
  script:
    - npm install -g firebase-tools
    - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    - tar xvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    - mv hugo /usr/local/bin/
    - ./build-site.sh
    - firebase use --token $FIREBASE_TOKEN major-io
    - firebase deploy -m "GitLab Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN
  cache:
    paths:
      - node_modules/
    key: "$CI_BUILD_REPO"
  only:
    - master
