routes:
  - route: "^.+\\.(js|css|svg|ttf|woff|woff2)$"
    headers:
      Cache-Control: "max-age=31536000, no-transform, public, immutable"
    gzip: true
  - route: "^.+\\.(png|jpg|jpeg|gif|ico|webp|avif)$"
    headers:
      Cache-Control: "max-age=31536000, no-transform, public, immutable"
    gzip: false
  - route: "^.+\\.(html|xml|json)$"
    headers:
      Cache-Control: "max-age=0, no-cache, no-store, must-revalidate"
    gzip: true
  - route: "^.*$"
    headers:
      Cache-Control: "max-age=86400, public"
    gzip: true
