baseurl: 'https://major.io/'
languageCode: en-us
theme: terminal
paginate: 5

# General Hugo configuration.
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
rssLimit: 25

params:
  contentTypeName: post
  themeColor: green
  showMenuItems: 5
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: true
  autoCover: true
  showLastUpdated: false
  readingTime: true
  Toc: false
  # TocTitle: Contents
  twitter:
    creator: '@majorhayden'
    site: '@majorhayden'
  # Site-wide opengraph/twitter cards.
  description: A social nerd writing about everything
  images:
    - /images/2019-05-24-cranes-skycrapers.jpg

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: w5wut
      name: W5WUT
      url: /w5wut/
      weight: 25
    - identifier: about
      name: About
      url: /cv/
      weight: 30

permalinks:
  posts: '/:year/:month/:day/:slug/'
languages:
  en:
    languageName: English
    title: "🤠 Major Hayden"
    subtitle: 'A social nerd writing about everything'
    owner: 'Major Hayden'
    keywords: ''
    copyright: All content CC-BY-SA
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Other posts I've written (some of them might even be good) 😉
    newerPosts: Read newer posts
    olderPosts: Read older posts
    missingContentMessage: Page not found...
    missingBackButtonLabel: Back to home page
    params:
      logo:
        logoText: "🤠 Major Hayden"
        logoHomeLink: /
