# General Hugo configuration
baseURL: "https://major.io/"
title: "Major Hayden"
paginate: 10
theme: terminal
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
rssLimit: 25

minify:
  disableXML: true
  minifyOutput: true

permalinks:
  posts: "/:year/:month/:day/:slug/"

params:
  contentTypeName: post
  themeColor: green
  showMenuItems: 5
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: true
  autoCover: true
  showLastUpdated: true
  favicon: "/favicon.ico"
  twitter:
    creator: "majorhayden"
    site: "major.io"
languages:
  en:
    languageName: English
    title: major.io
    subtitle: "A social nerd writing about everything"
    owner: "Major Hayden"
    keywords: "linux, technology"
    copyright: "&copy; Major Hayden"
    menuMore: Show more
    readMore: Read more
    readOtherPosts: Read other posts
    newerPosts: Newer posts
    olderPosts: Older posts
    missingContentMessage: Page not found...
    missingBackButtonLabel: Back to home page
    params:
      logo:
        logoText: "🤠 major.io: A social nerd writing about everything"
        logoHomeLink: /
    menu:
      main:
        - identifier: cv
          name: CV
          url: /cv
        - identifier: github
          name: GitHub
          url: https://github.com/major
        - identifier: twitter
          name: Twitter
          url: https://twitter.com/majorhayden
