baseURL: "https://major.io/"
languageCode: en-us
title: "major.io"
theme: lanyon
copyright: '&copy; Major Hayden'
canonifyURLs: false
relativeURLs: true
paginate: 5
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
rssLimit: 25
permalinks:
  post: '/:year/:month/:day/:slug/'
params:
  Title: "major.io"
  Tagline: "words of wisdom from a systems engineer"
  Author: Major Hayden
  DateForm: "2006-01-02"
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
author:
  name: Major Hayden
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed/index"
menu:
  main:
    - weight: '1'
      name: Home
      url: /
    - weight: '2'
      name: About
      url: /about
