baseURL: "https://major.io/"
languageCode: en-us
title: "major.io"
theme: terminal
copyright: "Made with 🥰 by Major Hayden and Hugo"
canonifyURLs: false
relativeURLs: true
paginate: 5
pygmentsCodeFences: 'true'
# pygmentsUseClasses: 'true'
pygmentsCodefencesGuessSyntax: 'true'
pygmentsStyle: 'solarized-dark'
rssLimit: 25
permalinks:
  post: '/:year/:month/:day/:slug/'
params:
  Title: "major.io"
  Tagline: "words of wisdom from a systems engineer"
  Author: Major Hayden
  DateForm: "2006-01-02"
  contentTypeName: "post"
  themeColor: "green"
  showMenuItems: 3
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: false
  logo:
    logoText: "major.io"
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
author:
  name: Major Hayden
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed/index"
menu:
  main:
    - weight: '20'
      name: "icanhazip"
      url: "/icanhazip-com-faq"
    - weight: '30'
      name: "Ham Radio"
      url: "/ham-radio-faq"
    - weight: '50'
      name: GitLab
      url: "https://gitlab.com/majorhayden"
    - weight: '60'
      name: GitHub
      url: "https://github.com/major"
    - weight: '40'
      name: "Talks & Presentations"
      url: "https://www.slideshare.net/MajorHayden/presentations"
    - weight: '70'
      name: "Résumé"
      url: "https://majorhayden.com/"