# Testing
baseURL = "https://major.io"
title   = "Major Hayden's Blog 🤠"
theme = "hugo-bearblog"

# Hugo global settings.
rssLimit  = 25
relativeURLs = true
buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true
enableRobotsTXT = true
enableEmoji     = true
enableGitInfo   = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/:year/:month/:day/:slug/"

[author]
  name = "Major Hayden"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  description = "Words of wisdom from a server administrator"
  favicon = "/favicon.ico"
  images = ["/images/2019-05-24-cranes-skycrapers.jpg"]
  title = "Major Hayden's Blog 🤠"
  dateFormat = "2006-01-02"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-light"
    tabWidth = 4

[menu]
  [[menu.main]]
    name       = "icanhazip FAQ"
    url        = "/icanhazip-com-faq"
  [[menu.main]]
    name       = "Ham Radio"
    url        = "/ham-radio-faq"
  [[menu.main]]
    name       = "Posts"
    url        = "/posts"

[social]
twitter = "mhayden"
